formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: .

sections:
  hide: []
  show: []

content: |-
  # Proxmox VM Terraform Module

  This module creates and manages Proxmox VMs using the Proxmox provider.

  ## Features

  - Full VM lifecycle management
  - Windows and Linux support
  - WinRM provisioning for Windows VMs
  - Cloud-init support
  - Multiple disk support
  - Multiple network interface support
  - Configurable CPU, memory, and storage
  - Template cloning
  - Flexible configuration via Terragrunt
  - Multi-VM deployment

  ## Usage

  ### Basic Example (Linux VM)

  ```hcl
  module "linux_vm" {
    source = "git::https://github.com/ginanck/terraform-proxmox-vm.git?ref=master"

    vms = {
      web-server = {
        vm_id       = 100
        name        = "web-server-01"
        ip_address  = "192.168.1.100/24"
        cpu_cores   = 2
        memory_dedicated = 4096
        disk_size   = 50
        tags        = ["web", "production"]
      }
    }

    clone_vm_id      = 8000  # Linux template
    network_bridge   = "vmbr0"
    init_gateway     = "192.168.1.1"
    init_dns_servers = ["8.8.8.8", "8.8.4.4"]
  }
  ```

  ### Windows VM Example

  ```hcl
  module "windows_vm" {
    source = "git::https://github.com/ginanck/terraform-proxmox-vm.git?ref=master"

    vms = {
      windows-server = {
        vm_id            = 200
        name             = "win-server-01"
        ip_address       = "192.168.1.200/24"
        cpu_cores        = 4
        memory_dedicated = 8192
        disk_size        = 100
        tags             = ["windows", "server"]
        
        # Windows-specific settings
        bios           = "ovmf"
        disk_interface = "sata0"
        is_windows     = true
        force_update   = false
        init_username  = "Administrator"
        init_password  = "SecurePassword123!"
      }
    }

    clone_vm_id      = 7902  # Windows template
    network_bridge   = "vmbr0"
    init_gateway     = "192.168.1.1"
    init_dns_servers = ["192.168.1.1"]
    is_windows       = true
  }
  ```

  ### Terragrunt Example

  See the [examples directory](https://github.com/ginanck/terraform-proxmox-vm/tree/master/examples) for complete Terragrunt configurations.

  ## Windows Support

  For Windows VMs, the module includes:
  - Automatic WinRM availability checks
  - PowerShell-based disk management provisioners
  - Configurable WinRM connection parameters

  ### Windows Requirements:
  1. Template must have Cloudbase-Init installed
  2. WinRM enabled on port 5985
  3. OVMF BIOS configured
  4. SATA disk interface

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
